### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by stuxt** [kazzkiq/balloon.css#10]
I want to know how the CSS browser is compatible.

**Comment by kazzkiq** [comment]
List of browsers:

:white_check_mark: = Checked and working
:no_entry_sign: = Checked and not working/compatible

**Desktop:**
- [x] FF (44+) :white_check_mark: 
- [x] Chrome (45+) :white_check_mark: 
- [x] Safari (9+) :white_check_mark: 
- [x] Edge :white_check_mark: (no tail)
- [ ] IE (11/10)
- [ ] IE (9)

**Mobile:**
- [x] FF :white_check_mark: 
- [x] Chrome :white_check_mark: 
- [x] Safari Mobile :white_check_mark: 

---

As I **do not** have Windows system, I cannot check the project on Edge/IE, same with iOS devices (although some folks reported it works well on iOS). Would be glad if someone could test on those browsers and give a feedback.

**Comment by stuxt** [comment]
I tested it on my windows machine.
IE (11/10)
IE (9/8/7-)
not working/compatible

**Comment by goranovs** [comment]
Windows 10
IE (Edge)

Works. Only arrows/tails are missing under the toolltips.

**Comment by kazzkiq** [comment]
@stuxt It isn't working even on IE 10/11?

@Zaifor The tail of the tooltips uses embedded `svg` directly on the `background` property. As every modern browser accepts this approach, I'm not sure if its a bug of Edge itself or just some missing adjustment.

**Comment by equinusocio** [comment]
If you use CSS 2.1 `:before` and `:after` (instead using CSS3 way `::`) will work on every browsers, also IE 8.

**Comment by kazzkiq** [comment]
@equinusocio Wow, now that's something I had no idea about. Will be updating the code with the fix tonight.

**Comment by kazzkiq** [comment]
@Zaifor @equinusocio Could you guys please test the new production files with Internet Explorer?

**Comment by curtismorte** [comment]
@kazzkiq for reference - [::before / ::after](https://css-tricks.com/almanac/selectors/a/after-and-before/)

Also, can we get a read me update once testing is done?

**Comment by kazzkiq** [comment]
@curtismorte Sure, once we test the changes on IE I will create a "Compatibility" section.

**Comment by goranovs** [comment]
No change here, but maybe the <button> tag is part of the problem for IE. On IE 11 ( 10 and 9 with DevTools ) it works with divs, but again no tail. Chrome have some issues with the text within divs.
[See the image](https://drive.google.com/file/d/0B_fJ4lx-vsEkSXJrdUVhb1R2eVE/view)

**Comment by kazzkiq** [comment]
@Zaifor the blurred text is related to issue #21. The fact that the tag still not working on IEs is provably due to use of inline SVG (Internet Explorer doesn't seem to play very well with non-basic SVG stuff).

**Comment by slavanga** [comment]
@kazzkiq the inline SVG must be URL encoded to work in IE.
Reduced test case: http://codepen.io/chriscoyier/pen/ZQgvyG/

**Comment by sbible** [comment]
IE10/11 work when the SVG is base64 encoded and an element other than button is used (div, span, a). IE9 partially works (the :before pseudo element is not center aligned correctly). And IE8, well that just fails.

Also, if support of browsers matching '> 1%, last 2 versions' (autoprefixer) is acceptable, a majority of the vendor prefixes are not needed, lightening up the code by almost 25%. IE9/10/11 all still work the same in that scenario.

**Comment by kazzkiq** [comment]
If there are any IE11 issues, please refer them to #47.
