### ISSUE TITLE
Compatibility with jQuery UI's icon-only buttons

### ISSUE THREAD

**Issue by claudix** [kazzkiq/balloon.css#100]
When using the jQuery-UI platform, buttons that are "icon only" (i.e. they just show up an icon but no text/caption) do not display the balloon's text. This is because the CSS rules affecting that type of buttons set the property `text-indent: -9999px`. Defining the rules below AFTER including balloon.css makes the trick and fixes this issue:

    [data-balloon]:after, [data-balloon]:before {
        text-indent: 0;
    }

I leave this comment just for people having similar issues. Feel free to use it for future versions.

**Comment by kazzkiq** [comment]
Added it to the code since other common frameworks/libs could also affect Balloon.css due to this.
