### ISSUE TITLE
how to change the tooltip font size

### ISSUE THREAD

**Issue by ShiranNasri** [kazzkiq/balloon.css#106]
how can i change the tooltip font size? and it is possible to use label instead button?

**Comment by kazzkiq** [comment]
>how can i change the tooltip font size?

As of today, you will have to use `!important` to override the `font-size` property in Balloon.css.

So a code like this would do the trick (use `.bigger-font` class in the element you want the tooltip to become larger):
```css
.bigger-font::after {
  font-size: 18px !important;
}
```

> and it is possible to use label instead button?

Yes, you can basically use any element which is not a [self-closing tag](http://xahlee.info/js/html5_non-closing_tag.html)

Example:
https://jsfiddle.net/sdog7mtq/

**Comment by ShiranNasri** [comment]
Thank you :)
