### ISSUE TITLE
Add to Bower?

### ISSUE THREAD

**Issue by smlombardi** [kazzkiq/balloon.css#11]
Would be excellent if this was added as a Bower package.

**Comment by nmaggioni** [comment]
You can still get it by issuing `bower install --save https://github.com/kazzkiq/balloon.css.git`.

**Comment by kazzkiq** [comment]
As discussed in #12, there is no intent into adding Balloon.css to Bower at the moment.

You can, however, install it using npm:

```
npm install balloon-css
```
