### ISSUE TITLE
FontAwesome example doesn't work

### ISSUE THREAD

**Issue by serious-angel** [kazzkiq/balloon.css#110]
Dear Developer,

Thank you for your library.
Although, check out a website. As you could notice, FontAwesome example doesn't work:

![img](https://i.imgur.com/ZeLw5hQ.png)

Best regards

**Comment by diomed** [comment]
@kazzkiq so what's up with that?

**Comment by diomed** [comment]
@kazzkiq that didn't fix github pages demo example, tho

**Comment by kazzkiq** [comment]
Yes, updating it and package version.
