### ISSUE TITLE
Use CSS Variables

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/balloon.css#117]
Make use of CSS Variables so users can easily update tooltip options even on production and dynamically.

**Comment by kazzkiq** [comment]
Done, now variables:

```
--balloon-color
--balloon-font-size
--balloon-move
```

Are exposed and can be used to customize tooltips.

**Comment by silverwind** [comment]
Would variables for padding like `--balloon-padding` be possible?

**Comment by kazzkiq** [comment]
@silverwind Yes! Please open a new Issue asking for it if you think is useful. I will then assign it to the next milestone.
