### ISSUE TITLE
Version 1.0 not working

### ISSUE THREAD

**Issue by ghost** [kazzkiq/balloon.css#118]
Since updating from version 0.5 to 1.0 the tooltips on my site no longer work (using Chrome 73). This is not just a problem with my site, I also tested the [JSFiddle](https://jsfiddle.net/9fboea3u/) linked to in the readme and it worked at first, but after I changed the balloon-css resource in the sidebar from version 0.3 to 1.0, the tooltips in the demo no longer work.

**Comment by kazzkiq** [comment]
Yes. `v1.0` is a major update and thus has breaking changes. It's not working in your website probably because we now use `aria-label` instead of `data-balloon`.

The new website will be released soon with instructions.

**Comment by kazzkiq** [comment]
[New website released](https://kazzkiq.github.io/balloon.css/).
