### ISSUE TITLE
Changing tooltip text color with variables

### ISSUE THREAD

**Issue by moeenio** [kazzkiq/balloon.css#121]
Would like to be able to change not only the background color but also the foreground color of the tooltips using available css variables like what we already have.

**Comment by kazzkiq** [comment]
By foreground you mean text color? That's actually an interesting feature.

**Comment by moeenio** [comment]
Lol, I didn't even remember about this thing.

**Comment by rmkane** [comment]
I offered a work-around here:

> https://github.com/kazzkiq/balloon.css/issues/70#issuecomment-612557655

**Comment by moeenio** [comment]
Well, this could easily be implemented as a CSS variable
