### ISSUE TITLE
Balloon is not displayed on IE11

### ISSUE THREAD

**Issue by nhh** [kazzkiq/balloon.css#129]
Balloon seems not to work in IE11.

This i mosty probably due to the pseudo elements being used.

Is there a way that we can make this happen in IE11? (I am pretty bad at CSS)

Would love to hear your suggestions!

**Comment by CocaColf** [comment]
That's because IE not support CSS variables, as the source code of this project shows,It used it.

**Comment by nhh** [comment]
Okay, thank you for your response! I‘m a little bit smarter now. ✌️😄
