### ISSUE TITLE
How to remove tooltip after clicking on the button?

### ISSUE THREAD

**Issue by emaillenin** [kazzkiq/balloon.css#135]
The tooltip doesn't automatically disappear after the button is clicked:

![tooltip-bug](https://user-images.githubusercontent.com/1235853/77742319-52ef8900-703c-11ea-82d3-36aceefead48.gif)

Can be reproduced on https://kazzkiq.github.io/balloon.css/ too.

I could reproduce this only with Chrome 80.0.3987.149 on Mac OS 10.14.6. 

Works fine with other browsers in the same OS.

**Comment by kazzkiq** [comment]
This is because by default Balloon.css also triggers on `:focus` states. Sometimes after you click a button, it remais focused.

To prevent this behavior you can use the `data-balloon-nofocus` attribute. E.g.:

```html
<!-- Will NOT appear on focus -->
<button aria-label="Hey!" data-balloon-pos="up" data-balloon-nofocus></button>
```

**Comment by moeenio** [comment]
If you use `nofocus`though, it won't appear when navigating with keyboard.
