### ISSUE TITLE
Tooltip does not appear when triggered for a svg <line> element

### ISSUE THREAD

**Issue by AlanKrygowski** [kazzkiq/balloon.css#151]
I'm trying to use tippy to display hover contents on a Chartist graph. 
When attempting to fire the tooltip on a svg `line` component, the tooltip itself does not show. 
```
<line x1="xxx" x2="xxx" y1="xxx" y2="xxx" class="ct-bar" ct:value="3" aria-label="3" data-balloon-pos="up" data-balloon-blunt="true"></line>
```
The very same configuration works for all other dom elements that have a closing tag.

**Comment by kazzkiq** [comment]
AFAIK SVG elements do not support pseudo elements (`::before` and `::after`).

This means it is not possible to use Balloon.css directly with SVG elements.
