### ISSUE TITLE
Not disappearing after click ( Angular Material 15.1.0)

### ISSUE THREAD

**Issue by jusfeel** [kazzkiq/balloon.css#178]
I think this is because the focus on the item is not being off-focus for some reason. 

This is happening on the latest update on the latest Material Angular v15.1.0.

When I click the link which is routing the app to a new route, the route changes yet the balloon keeps showing until I click some where on the page , then it goes away ( I think because the focus on the button is changed).

Not sure what exactly happening, I think it's related to how angular deal with the focus when route changes. 

![image](https://user-images.githubusercontent.com/2442286/212536937-2bb8f989-e3ad-4f9e-bafb-029d7230586a.png)

**Comment by SanjeevSingh08** [comment]
> I think this is because the focus on the item is not being off-focus for some reason.
> 
> This is happening on the latest update on the latest Material Angular v15.1.0.
> 
> When I click the link which is routing the app to a new route, the route changes yet the balloon keeps showing until I click some where on the page , then it goes away ( I think because the focus on the button is changed).
> 
> Not sure what exactly happening, I think it's related to how angular deal with the focus when route changes.
> 
> ![image](https://user-images.githubusercontent.com/2442286/212536937-2bb8f989-e3ad-4f9e-bafb-029d7230586a.png)

I think we should make a function -
Whenever we click on the button the hover effect should be removed after a time-span say-2seconds
