### ISSUE TITLE
Text on demo page appears fuzzy

### ISSUE THREAD

**Issue by mattl** [kazzkiq/balloon.css#26]
http://kazzkiq.github.io/balloon.css/

The "GitHub Project" and "Download CSS" hover baloons are fuzzy/blurry. Others are okay.

![screenshot from 2016-03-15 14-54-33](https://cloud.githubusercontent.com/assets/33296/13792052/f4f2ed90-eabd-11e5-9a4a-7b665ed6fd18.png)
![screenshot from 2016-03-15 14-54-30](https://cloud.githubusercontent.com/assets/33296/13792053/f4f7c6ee-eabd-11e5-98e3-b34cf53e4a4f.png)

https://aboutmybrowser.com/NlLd49Rv

**Comment by BTMorton** [comment]
I get this in my Chrome version as well. Managed to remove it by changing the transform: translate3d to be a transform: translate if it helps

Edit: Ah, just noticed this was reported seperately by @spaghetti2514 #21

**Comment by kazzkiq** [comment]
PR #33 fixes this issue. This fix is available from version 0.2.4 and beyond.
