### ISSUE TITLE
fixed tooltip

### ISSUE THREAD

**Issue by wallace7souza** [kazzkiq/balloon.css#27]
Is there a way to fixed tooltip?
I need this to indicate a update in on page

**Comment by kazzkiq** [comment]
What do you mean by "fixed tooltip"?

**Comment by wallace7souza** [comment]
Bootstrap has a similar behavior but use javascript
![image](https://cloud.githubusercontent.com/assets/3328434/13800618/92590dda-eb09-11e5-966b-15a00592b80e.png)

**Comment by kazzkiq** [comment]
This can be done, but would require a few changes. I may take a look at it this week.

**Comment by kazzkiq** [comment]
Commit 58d2cae added this option. Now you can use the attribute `data-balloon-visible` to force tooltips visible even when not hovering the element.
