### ISSUE TITLE
IE11 has a lot of bugs

### ISSUE THREAD

**Issue by sasha-bichkov** [kazzkiq/balloon.css#36]
I've just checked [balloon.css](http://kazzkiq.github.io/balloon.css/) by using [browserstack](www.browserstack.com) and found some bugs in IE11. Unfortunately, according to this article [browsers_stats](http://www.w3schools.com/browsers/browsers_stats) IE11 have 6.1% (March, 2016) of active users, but according to the another article even more (~10%). I think it should be fixed and README.md should contain information about supported browsers as well, because I'm not willing to sacrifice of my users.

**Comment by kazzkiq** [comment]
Could you please provide screenshots and describe better what issues you're having on this browser? Some folks on #10 described it working alright, the only issue being arrows not showing.

**Comment by BTMorton** [comment]
If it's any help, it seems that the tooltips don't work on button elements, but are fine on anchors. Maybe it's something blocking :after on IE? Oh, and the :before arrows don't seem to work either

**Comment by kazzkiq** [comment]
Commit 3f9ff39 solved the button Issue. If there are any other bugs on IE11 please use Issue #47 .
