### ISSUE TITLE
Tooltip styling affected by element

### ISSUE THREAD

**Issue by seemantk** [kazzkiq/balloon.css#37]
Hello.  Thank you for this.  It is much improved over hint.css.  Also, great to see that you are actively maintaining.

I've noticed that the tooltips adopt some styles from the element being tooltipped.

A couple of uses cases:
1. opacity is the same as the element's opacity.
   - The workaround was straightforward enough in my case (to , put the data attributes on the element, and stick the text in a child <span> and apply opacity to that span - it's a bit klunky adding elements, but not a big deal.
2. `<strong>` text in the element leads to `<strong>` text in the tooltip.  With data-attributes on a an `<h5>` element (using bootstrap base styling) the tooltip text is bold.  No workaround that I've been able to find here. 

Here's a link to see: http://seemantk.com/viz/brennan (The tooltips over the bar charts, bar chart labels, and the 3 lists below (Interim Selection, First Full Term, Additional Terms.  The tooltips on the map are from d3-tip, as balloon-css doesn't work on SVG).

Cheers,
Seemant

**Comment by kazzkiq** [comment]
Wow @seemantk I did not knew this hint.css project! Looks very cool (I would even say more feature-rich than Balloon.css). But I guess I still prefer to stick to simpler and tinier approach (biased opinion, I know) 😄.

About the issue... while I ~~hate~~ am not a big fan of `!important`, I can't see a better solution than using it will on this issue. Will be taking a look at it soon.

**Comment by agauniyal** [comment]
@seemantk I do this in sass for temp workaround,

``` lang=scss
[data-balloon] {
  &:after,
  &:before,
  &:hover:before,
  &:hover:before {
    font-family: sans-serif;
  }
}
```

**Comment by kazzkiq** [comment]
> 1. opacity is the same as the element's opacity.

I believe this is not solvable. Since opacity is a relative property (its value is relative to its parent value), there is no way to re-enable opacity if the parent element removes it. The solution here is removing the opacity from the parent in your project.

> \<strong\> text in the element leads to \<strong\> text in the tooltip (...)

I'm pushing a commit that force text reset on all tooltips (using @agauniyal workaround), that solves the issue.
