### ISSUE TITLE
How to set NewLine?

### ISSUE THREAD

**Issue by ekatherina** [kazzkiq/balloon.css#39]
I tried data-balloon="Test test & # 13;& # 10; Test Test.\A Test Test <br> & # x a; Test Test" - but no one of them helps.
How can I break text in ballon to new line?

Thank you.

**Comment by kazzkiq** [comment]
@ekatherina there are two ways to break lines in Balloon tooltips:

#### Option 1: Manually adding line-breaks:

You need to write the code `&#10;` without spaces, and use the attribute **`data-balloon-break`**. E.g.

``` html
<span data-balloon="Line one &#10; Line two" data-balloon-break>This is a tooltip</span>
```

#### Option 2: Using `data-balloon-length` to break lines automatically:

Additionally you can also let the tooltip break automatically using the length attribute:

``` html
<span data-balloon="I'm a big text that don't breaks automatically bla bla bla bla." data-balloon-length="small">This is a tooltip</span>
```

The values for **`data-balloon-length`** are: **`small`**, **`medium`**, **`large`** and **`fit`**. You can check examples for length on the website, in "Length" section.

**Comment by iamdevlinph** [comment]
``` css
<span data-balloon="Line one &#10; Line two" data-balloon-break>This is a tooltip</span>
```

doesn't seem to work

**Comment by iursevla** [comment]
If someone is doing this programatically, instead of  `&#10;` use `\n` and follow the other instructions provided by @kazzkiq

**Comment by Georgiy-G** [comment]
I try repeat code, but I have extra commas
![image](https://user-images.githubusercontent.com/19470940/60820382-02808480-a1aa-11e9-9c22-677fd9bc1220.png)
https://codesandbox.io/s/cool-wood-kso0e

**Comment by ghost** [comment]
I was using balloon.css in EJS
Simply putting attribute as _**data-balloon-break**_     didn't worked for me (strange) . Setting  **data-balloon-break=""**    worked perfectly✔️  with '\n'

**Comment by daattali** [comment]
This feature should be mentioned in the docs
