### ISSUE TITLE
Add autoprefixer in build

### ISSUE THREAD

**Issue by anthony-redFox** [kazzkiq/balloon.css#44]
Hard coded prefixes like webkit, ms, moz looks not so good.
[autoprefixer](https://github.com/postcss/autoprefixer)

**Comment by kazzkiq** [comment]
As of now I believe most browsers don't require prefixes anymore. Balloon.css is a library focused (mainly) on modern browsers, so I see no advantage in adding yet another package to the project just to generate prefixes.

Let the elderly browsers die. :-P
