### ISSUE TITLE
IE11 Compatibility Issues

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/balloon.css#47]
All issues and bugs related to IE11 (**and IE11 ONLY**) must be added in this Issue.

**Screenshots of the bug are encouraged.**

**Comment by anthony-redFox** [comment]
I think, the issue should be closed by 23fc90b and 3f9ff39 commit.

**Comment by kazzkiq** [comment]
As no one bought any other IE11 related bug, I'm going to close this issue.
