### ISSUE TITLE
IE10 hover issue

### ISSUE THREAD

**Issue by zedissime** [kazzkiq/balloon.css#49]
Hello,
I don't know if I did something wrong as I didn't saw any issue related. 
But on IE10 I had an issue where the tooltip was appearing if the mouse was hover the :after element, and not hover the tooltip himself. It's an issue related to the pointer-events:none which is not working < IE11.

I made a quick and dirty fix where I set by default a z-index: -1 to [data-balloon]:after and :before
and on :hover I set back the z-index to 10.

**Comment by ravikumar9873** [comment]
Hello All,

I am having the same issue. When I try to mouse hover on IE, it marks the status as pass but in actual, mouse hover doesn't happen.
I am trying to figure out this problem by using selenium+java in internet explorer.
I am using the same code for chrome and that is working fine but not working with IE10 and 11.

Please help.

**Comment by mtsweir** [comment]
Seems to help resolve issues in IE < 10. IE 11 works fine from initial tests.

The only downside is the arrow is positioned below the text box, using a higher z-index for the arrow will through the timing out when both elements fade out.

**Comment by ghost** [comment]
We have the same issue described here but with  Chrome on 10.12.2 OSX @ CHROME 61.0.3163.100

Also fixed by applying the z-index -10 trick. Thanks,

**Comment by kazzkiq** [comment]
Balloon.css has no intent to work on IE 10. And `v1.0` will drop official support for IE11 too.

If you really need tooltips for legacy browsers you will have to implement hotfixes on top of Balloon.css or look for a legacy tooltip library.
