### ISSUE TITLE
Enhancement: Add attribute to always show tooltip

### ISSUE THREAD

**Issue by benmarte** [kazzkiq/balloon.css#50]
I needed to be able to show a tooltip programmatically so I ended up doing something like this:

```[data-balloon-show="true"]:after,
[data-balloon-show="true"]:before{
  opacity: 1 !important;
}

[data-balloon-show="false"]:after,
[data-balloon-show="false"]:before{
  opacity: 0 !important;
}

[data-balloon-show="true"]:after,
[data-balloon-show="true"]:before,
[data-balloon-show="true"][data-balloon-pos="down"]:after,
[data-balloon-show="true"][data-balloon-pos="down"]:before{
  -webkit-transform: translate(-50%, 0);
  -ms-transform: translate(-50%, 0);
  transform: translate(-50%, 0);
}

[data-balloon-show="true"][data-balloon-pos="left"]:after,
[data-balloon-show="true"][data-balloon-pos="left"]:before{
  -webkit-transform: translate(0, -50%);
  -ms-transform: translate(0, -50%);
  transform: translate(0, -50%);
}

[data-balloon-show="true"][data-balloon-pos="right"]:after,
[data-balloon-show="true"][data-balloon-pos="right"]:before{
  -webkit-transform: translate(0, -50%);
  -ms-transform: translate(0, -50%);
  transform: translate(0, -50%);
}
```

So if I want to always display a tooltip I can just add data-balloon-show attribute to my element and it will display. Just sharing this in case someone else needs it or if you want to add this to the lib.

Thanks.

**Comment by kazzkiq** [comment]
@benmarte Actually there is an attribute for this task already: `data-balloon-visible`. Adding it to any tooltip will make them always visible (regardless of mouse/touch interaction).

Example:

``` html
<button data-balloon="Always visible!" data-balloon-pos="up" data-balloon-visible>Label here</button>
```

Looking through the documentation I guess I forgot to add this feature there. It went more like an easter-egg it seems. My bad. 😅

**Comment by benmarte** [comment]
HA! I saw that and paid no mind to it, you should update the docs though to include it if you can ;)

Thanks for replying and good job on this, works great.

**Comment by kazzkiq** [comment]
Docs and website updated! 👍
