### ISSUE TITLE
Optional Transition

### ISSUE THREAD

**Issue by brunoaugusto** [kazzkiq/balloon.css#53]
Not an issue, just something I came up while thinking about having the possibility to not have the easing animation, making it optional, so I created a new *data-attribute* to remove it:

```
[data-balloon-static]:after, [data-balloon-static]:before {
    -webkit-transition: none;
    transition: none;
}
```

With this if one needs the Balloon without the animation just need to add to the markup:

```
<button data-balloon-length="small" data-balloon="Hi." data-balloon-static>Hover me!</button>
```

And, of course, congratulations for the awesome work ;)

**Comment by kazzkiq** [comment]
Awesome idea! Would you like to send a PR with this implementation, or I could add it myself if you want to. 👍

**Comment by brunoaugusto** [comment]
I'd prefer you to add it yourself because I don't have much experience with the collaborative side of GIT

**Comment by kazzkiq** [comment]
Done.

Now you can use `[data-balloon-blunt]` to force tooltips without animations.
