### ISSUE TITLE
Wrap at screen edge?

### ISSUE THREAD

**Issue by FoxInFlame** [kazzkiq/balloon.css#59]
Hey, thank you for making this CSS library.

I'm using the generated CSS file, and while using this, I noticed that tooltips are being cut off by the screen edge.

Is there a way for tooltips/balloons to wrap at the end of the screen?

![Imgur](http://i.imgur.com/j5jM5kS.png)

**Comment by kazzkiq** [comment]
Issue related to #62. This enhancement must come in v0.5.0.

Closing this issue to let #62 be the main thread.

**Comment by FoxInFlame** [comment]
It is related, but it shouldn't be something the creator chooses. It should automatically wrap if it's at the edge, and show normally (equal margin on both side) if it doesn't meet any edges.
