### ISSUE TITLE
Limited to button elements?!

### ISSUE THREAD

**Issue by ErinPo** [kazzkiq/balloon.css#61]
How to have tooltip over normal text within a paragraph?

**Comment by kazzkiq** [comment]
You can simply use an inline element such as `<span>` for this purpose.

**Comment by ErinPo** [comment]
I wish... but it fails on iOS.

**Comment by kazzkiq** [comment]
Hmm it seems iOS only shows tooltips on clickable elements (buttons, links, etc). Looks like a bug.

**Comment by ErinPo** [comment]
Yeah, I found out Safari has been like that for years. It's not a bug to count on Apple fixing. I was able to fix it by adding `onclick="void(0)"` to the `span`. Now the only iOS shortcoming left is that you cannot click away to remove focus and hide the tooltip. Any idea on that?

**Comment by renatodeleao** [comment]
@ErinPo that might be related with [this](https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile), and this should do the trick.

```css
 .your-interactive-element { cursor: pointer}
```

Other readings:
[Bootstrap tooltip issue](https://github.com/twbs/bootstrap/issues/16028)
[stackoverflow](http://stackoverflow.com/questions/18047353/fix-css-hover-on-iphone-ipad-ipod)

**Comment by kazzkiq** [comment]
The commit d4b2e5955f27dfc7db7c0358988413d1bb32927c adds your workaround, @renatodeleao. Thanks for the info!
