### ISSUE TITLE
Suggestion: open top-left/right or bottom-left/right instead of left/right

### ISSUE THREAD

**Issue by ErinPo** [kazzkiq/balloon.css#62]
It seems left/right display options primary purpose to handle narrow screen situations like smartphone in portrait orientation. However better use of space could be achieved in this scenario by keeping the balloon above or below the trigger but extending it to the left or right only instead of the default to both sides equally. Do you know what I mean?

**Comment by jhudson8** [comment]
+1 that would be an exceptional enhancement

**Comment by wwwjun** [comment]
+1

**Comment by kazzkiq** [comment]
Will be taking a look at it as soon as possible.

**Comment by brainmaniac** [comment]
+1

**Comment by kazzkiq** [comment]
Feature added.

Now you can use `up-left`, `up-right`, `down-left` or `down-right` into `[data-balloon-pos]` to get tooltips that are aligned to that side (and grow only to the opposite side).

### Example:

<img width="342" src="https://user-images.githubusercontent.com/1953194/29282357-f0c43f6c-80f8-11e7-95d2-ef41a523fd74.png">

**Comment by nihique** [comment]
nice, thank you :)
