### ISSUE TITLE
allow variables to be overridden

### ISSUE THREAD

**Issue by frazjp65** [kazzkiq/balloon.css#67]
There is no easy way to override the background color, or any other variables in SASS. 

Can this be changes so that: 

```scss
$balloon-bg:             fade-out(#111, .1);
$balloon-base-size:      10px;
$balloon-arrow-height:   6px;
```

Looks like: 

```scss
$balloon-bg:             fade-out(#111, .1) !default;
$balloon-base-size:      10px !default;
$balloon-arrow-height:   6px !default;
```

This would allow us to set the variables in our SASS before importing this library. 

I am not sure how to do this in LESS.

**Comment by frazjp65** [comment]
It looks like this is handled in PR #52.

**Comment by kazzkiq** [comment]
Closing this as #52 fixes the issue.
