### ISSUE TITLE
Please create a new release for SASS default variables

### ISSUE THREAD

**Issue by georgiana-gligor** [kazzkiq/balloon.css#69]
Currently installing this library from `npm` does not include the defaults for the `sass` variables.

I have tested that they work by manually applying this code to my local `node_modules` code and overwriting the default tooltip background color.

Please tag a newer release to include this fix, that came in pull request #52 .

**Comment by kazzkiq** [comment]
Done.

https://www.npmjs.com/package/balloon-css

**Comment by georgiana-gligor** [comment]
Thank you!
