### ISSUE TITLE
Balloon.css + Carbon

### ISSUE THREAD

**Issue by sayzlim** [kazzkiq/balloon.css#74]
Hi Claudio,

Would love to invite you to join [Carbon](https://carbonads.net/) and generate some revenue by displaying an ad on the project. Would you be interested? Could you share with me your email address so I can send more details with you?

**Comment by kazzkiq** [comment]
Sure, @sayzlim!

Here is my e-mail:

<img width="177" alt="captura de tela 2017-10-05 as 11 10 40" src="https://user-images.githubusercontent.com/1953194/31231663-dac336a8-a9bd-11e7-87d6-86d9ec858e41.png">

**Comment by sayzlim** [comment]
@kazzkiq I’ve sent the email to you. Looking forward to hear your feedbacks.
