### ISSUE TITLE
Should we keep LESS support?

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/balloon.css#77]
As Balloon.css evolves and receives more and more PRs with quite advanced features, its getting harder to maintain two versions of source-code (Sass and LESS).

Since Sass became basically the *lingua-franca* of CSS pre-processors, and since virtually all PRs are made in Sass, I see no reason to keep updating LESS too. In the end, the final code will always compile to pure CSS anyways.

So, what do you folks think? Should Balloon.css keep only one source file (Sass), simplifying the development and deployment of new versions? Should we still keep maintaining both LESS and SASS?

**Comment by cthedot** [comment]
TBH the amount of (generated) CSS hardly justifies a CSS preprocessor at all but if you like to keep it just keep SASS. BTW any reason why prefix support goes all the way back with kthml and even IE (old) filters? Maybe time to review browser support?

**Comment by muhammadmuzzammil1998** [comment]
I always wondered why there are 2 sources to Balloon.css. 😂
Its like what you said, "In the end, the final code will always compile to pure CSS anyways." So, I, personally, think that there's no reason to keep less version.

By the way, love Balloon.css.

**Comment by NoorMkdad** [comment]
If a LESS version is becoming to difficult to manage and it's not getting that many PRs making you have to possibly make the changes to the LESS version yourself just get rid of it

**Comment by kazzkiq** [comment]
Dropped LESS. Details and commits here: #113.
