### ISSUE TITLE
Update CDN link

### ISSUE THREAD

**Issue by iursevla** [kazzkiq/balloon.css#80]
In the README.md there is:

> CDN version (provided by cdnjs):
> `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/balloon-css/0.2.4/balloon.min.css">`

But this version is old. I was using it and couldn't use tooltips programattically. The problem was that the `data-balloon-visible` attribute did not exist in version 0.2.4

So it should be changed to version 0.5.0:

> CDN version (provided by cdnjs):
> `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/balloon-css/0.5.0/balloon.min.css">`

**Comment by kazzkiq** [comment]
Nice catch. I've updated the readme.
