### ISSUE TITLE
align tooltip top-left, top-right, bottom-left, bottom-right

### ISSUE THREAD

**Issue by vasyl-shumskyi** [kazzkiq/balloon.css#83]
Hello,

Thanks for amazing tooltip! 

I faced with small issue trough (see screenshot). 

<img width="784" alt="screen shot 2017-10-21 at 16 28 18 copy" src="https://user-images.githubusercontent.com/2331802/31852261-738fa77e-b67d-11e7-9418-5727bfae465c.png">

In my case it would be nice to align tooltip bottom-left from the element.

So the question is - Is it possible to align tooltip top-left, top-right, bottom-left, bottom-right

Like so: 
https://ant.design/components/tooltip/#components-tooltip-demo-placement

<img width="468" alt="screen shot 2017-10-21 at 16 25 25" src="https://user-images.githubusercontent.com/2331802/31852210-7e443e2e-b67c-11e7-9510-b0ba402ff8bb.png">

Any other workaround would be appreciated as well. 

Thanks!

**Comment by kazzkiq** [comment]
Yeah, it was added in `v0.5.0`. You can check the positioning options [in the readme](https://github.com/kazzkiq/balloon.css#positioning).

In your case it would be `data-balloon-pos="down-right"`:

```html
<button data-balloon="Whats up!" data-balloon-pos="down-right">Hover me!</button>
```

Example: https://jsfiddle.net/eh1wkr1t/

**Comment by vasyl-shumskyi** [comment]
Oh, that's amazing. I think website just lacking this info http://kazzkiq.github.io/balloon.css/ Shame on me for missing this info on Github..

Thanks!
