### ISSUE TITLE
Adding data-balloon-delay

### ISSUE THREAD

**Issue by iplanwebsites** [kazzkiq/balloon.css#85]
When using on a large number of consecutive elements, it's annoying and inefficient for users to wait for the tooltip to show up.
I suggest adding a `transition` or `delay` property to be able to speed up or disable the sliding transitions.

**Comment by thibaudcolas** [comment]
There is already `data-balloon-blunt` to disable the transitions. This may not be appropriate if you only want to speed them up, but might help.

**Comment by krns** [comment]
Would love to see this feature!

**Comment by kazzkiq** [comment]
Closing this as `data-balloon-blunt` does the trick.
