### ISSUE TITLE
Tooltip on focus

### ISSUE THREAD

**Issue by dusterbed** [kazzkiq/balloon.css#86]
Can we add the ability to show tooltip on focus for keyboard users? Currently css is only for hover. :)

**Comment by fractaledmind** [comment]
This is a feature slated for the next release and is a part of this PR: https://github.com/kazzkiq/balloon.css/pull/56

**Comment by Rainbowlemon** [comment]
Adding `:active` as well would allow for touchscreens to be able to see the tooltips. As of now, I've had to ditch usage of this plugin for something that'll work on mobile.

**Comment by kazzkiq** [comment]
Closing this as with v1.0 (being released soon) tooltips will accept :focus by default and will also make use of aria-label.
