### ISSUE TITLE
Using data-balloon on a table cell

### ISSUE THREAD

**Issue by shlomih87** [kazzkiq/balloon.css#88]
Hi,

I'm trying to use the balloon in order to elaborate more on data in a table cell.
I've tried to do something like this:
\<td data-balloon="ABC"  #data-balloon-pos="up"\>ABC\</td\>
And the balloon just doesn't show up.

Currently in our project the balloon is just used with the <a> tag, not in the context of a table.
I figured the issue might have to do with the table.

Please help me with that :)

Thanks,
Shlomi

**Comment by kazzkiq** [comment]
It seems you added a hashtag (#) in the `data-balloon-pos` attribute which may be preventing tooltips to work properly.

So, to clarify:

```html
<!-- Your code -->
<td data-balloon="ABC" #data-balloon-pos="up">ABC</td>
<!-- Should be -->
<td data-balloon="ABC" data-balloon-pos="up">ABC</td>
```

Here is an example showing Balloon.css works fine with `<td>`: https://jsfiddle.net/xte71ffv/
