### ISSUE TITLE
CSS columns z-index issue, tooltip disappears

### ISSUE THREAD

**Issue by CodeBrauer** [kazzkiq/balloon.css#89]
Check this demo: https://codepen.io/gab/pen/mpLYEL on Chome 63 (current stable)

Hover of the "3" or any number higher 15, the tooltip has a z-index issue and disappears after the animation.

probably related: https://github.com/chinchang/hint.css/issues/60

**Comment by kazzkiq** [comment]
This looks like a rendering error that changes behavior occasionally upon browser engine updates. I don't think the library can do anything at the moment to fix the underlying engine issues.

Any fix would be welcome though.
