### ISSUE TITLE
Tooltip breaks lines only on space or dash

### ISSUE THREAD

**Issue by vasyl-shumskyi** [kazzkiq/balloon.css#91]
Hello,

Looks like tooltip auto-break lines on spaces and dashes only. If we have looooooong enough line without these symbols (lets say `/long/file/path`) with `data-balloon-length="medium"` - the text not breaking correctly and appears to be out off tooltip. 

How to make tooltip text breakable on other symbols? 
In my case on forward and back slashes `/` or `\`

**Comment by kazzkiq** [comment]
Its a bug.

Until there is a new release, you can fix locally by adding this CSS:

```css
[data-balloon-length] {
  word-break: break-word;
}
```
