### ISSUE TITLE
tooltips can not show fully if container's height is not enough

### ISSUE THREAD

**Issue by chuduyunhuan** [kazzkiq/balloon.css#93]
Hi,

Code may be like this:
<div style="height: 60px;">
    <button 
        data-balloon='just a test' data-balloon-pos="down"
    >Hover Me</button>
</div>
How can i do with it such as set the z-index?

Thanks a lot.

**Comment by chuduyunhuan** [comment]
Sorry, the code didn't show up. You may take a look at this demo.
http://jsbin.com/guzunegumo/1/edit?html,css,output
Thanks.

**Comment by kazzkiq** [comment]
The problem here is not the height, but the `overflow: hidden`. When the parent element has `hidden` or `scroll` on its `overflow` property, its impossible to show any children out of its boundaries.

Check the discussion in #92 for more details.
