### ISSUE TITLE
Could the date-of-creation, the year, when balloon .css was created, be added? Just a short line perhaps?

### ISSUE THREAD

**Issue by ghost** [kazzkiq/balloon.css#97]
Hello Claudio and others,

Could a tiny section be added to say in which year balloon.css has been created?

I am merely curious but perhaps others are too, so perhaps that could be added to
the main README if you have the time to do so.

Cheers!

**Comment by kazzkiq** [comment]
My first commit dates back from Mar 1, 2016. Balloon is a little more than 2 years old as of today.

I'm not sure if "creation date" is much relevant, but perhaps we can add it to README someday.
